Basic information on migration lifecycle
flarum/docs pull request #150
Opened 2020-11-26 18:10 UTC by Swader

2020-11-26 22:10 UTC, askvortsov1 requested changes

2020-11-26 22:10 UTC, askvortsov1 commented on docs/extend/data.md
> +Migrations can also be manually applied with `php flarum migrate` which is also needed to update the migrations of an already enabled extension. To undo the changes applied by migrations, you need to
Nothing can break by running `migrate`  => Nothing can break by running `php flarum migrate`

2020-11-27 09:34 UTC, luceos approved these changes

2020-11-27 14:06 UTC, askvortsov1 approved these changes

2020-11-27 14:06 UTC, merged