Update for Beta 15
flarum/docs pull request #152
Opened 2020-12-15 02:01 UTC by askvortsov1

- Beta 15 upgrade guide
- Update to use new extenders
- Document api throttling
- Document service provider layer
- Add documentation of API request lifecycle
- Document `parse` and `render` for formatter
- Update recommended extension version constraints
- Add blank pages for model slugging @tankerkiller125  and admin UX @KyrneDev

2020-12-15 02:15 UTC, tankerkiller125 commented on docs/extend/api-throttling.md
> +Any other outputs will be ignored. If the throttler allows a given request, it should probably return `null` (or not return anything), not `true`.
Why not just take the note/comment about null and make it a 3rd response?

2020-12-15 12:02 UTC, clarkwinkelmann requested changes

2020-12-15 12:16 UTC, SychO9 commented on docs/extend/data.md
> +4. The `$this->data()` method of the controller is called, yielding some raw data that should be returned to the client. Typically, this data will take the form of a Laravel Eloquent model collectio
also the data can be a simple php array

2020-12-15 19:51 UTC, askvortsov1 commented on docs/extend/data.md
> +2. The request is run through [middleware](middleware.md), and routed to the proper controller. You can learn more about controllers as a whole on our [routes and content documentation](routes.md). A
Plural of middleware is middleware

2020-12-15 19:52 UTC, askvortsov1 commented on docs/extend/data.md
> +4. The `$this->data()` method of the controller is called, yielding some raw data that should be returned to the client. Typically, this data will take the form of a Laravel Eloquent model collectio
> Is the method really called data for each type of controller?

Yep!

2020-12-16 22:53 UTC, clarkwinkelmann commented on docs/extend/data.md
> +2. The request is run through [middleware](middleware.md), and routed to the proper controller. You can learn more about controllers as a whole on our [routes and content documentation](routes.md). A
Didn't know that :hankey: 

Still sounds confusing to me. What about "the middleware pipe" then?

2020-12-16 22:56 UTC, clarkwinkelmann approved these changes
I added a suggestion in reply to my previous review. Otherwise all good!

2020-12-18 13:13 UTC, merged