Update Translation to include "Tip" flarum-lang
flarum/docs pull request #348
Opened 2021-07-02 06:46 UTC by GreXXL

Including flarum-lang in the tip-section of the translation page

2021-07-03 17:14 UTC, tankerkiller125 approved these changes

2021-07-03 18:24 UTC, davwheat requested changes

2021-07-03 18:24 UTC, davwheat requested changes

2021-07-03 18:24 UTC, davwheat commented on docs/extend/language-packs.md
> +The Flarum Foundation is supporting translators while ensuring continous availibilty of language packs. Therefor "flarum-lang" was initiated. You can learn all about this by visiting the [GIT reposit
```suggestion
The Flarum Foundation have created the "flarum-lang" organization to support translators and ensure continuous availability of language packs. You can learn all about this by visiting the [GitHub repository](https://github.com/flarum-lang/about). If you want to support an existing language pack or start a new translation, it's best to [get in touch with the flarum-lang team](https://discuss.flarum.org/d/27519-the-flarum-language-project).
```

2021-07-15 12:12 UTC, davwheat commented on docs/extend/language-packs.md
> +The Flarum Foundation have created the "flarum-lang" organization to support translators and ensure continuous availability of language packs. You can learn all about this by visiting the [GitHub rep
```suggestion
The Flarum Foundation has created the "flarum-lang" organization to support translators and ensure continuous availability of language packs. You can learn more about this by [visiting the GitHub repository](https://github.com/flarum-lang/about). If you want to support an existing language pack or start a new translation, it's best to [get in touch with the `flarum-lang` team](https://discuss.flarum.org/d/27519-the-flarum-language-project).
```

2021-07-15 12:12 UTC, davwheat approved these changes

2021-07-15 12:13 UTC, merged