Update install.md
flarum/docs pull request #352
Opened 2021-07-09 13:25 UTC by justoverclockl

updated italian docs

2021-07-09 13:29 UTC, davwheat approved these changes

2021-07-09 14:38 UTC, datitisev commented
Do we want to remove the `.`? Is that the default install directory?

2021-07-09 16:46 UTC, davwheat commented
Good spot!

2021-07-09 22:40 UTC, datitisev requested changes
Don't remove the `.` relative path.

2021-07-15 16:33 UTC, justoverclockl commented
i have to do something? 👀

2021-07-15 16:36 UTC, davwheat commented on docs/it/install.md
> +composer create-project flarum/flarum
```suggestion
composer create-project flarum/flarum .
```

2021-07-15 16:36 UTC, davwheat approved these changes

2021-07-17 20:28 UTC, luceos approved these changes

2021-07-17 20:29 UTC, merged